apiVersion: v1
kind: Service
metadata:
  name: marca-api
  namespace: inregistrare-marca
  labels:
    app.kubernetes.io/name: marca-api
spec:
  selector:
    app.kubernetes.io/name: marca-api
  ports:
    - name: http
      port: 3000
      targetPort: 3000
