apiVersion: v1
kind: Secret
metadata:
  name: marca-api-secrets
type: Opaque
stringData:
  RAILS_MASTER_KEY: replace-with-api-config-master-key
  SECRET_KEY_BASE: replace-with-rails-secret-key-base
  DATABASE_PASSWORD: replace-with-mysql-app-password
