apiVersion: v1
kind: PersistentVolume
metadata:
  name: marca-mysql-data
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: marca-local
  hostPath:
    path: /home/storage/ns/inregistrare-marca/marca-mysql-0
    type: DirectoryOrCreate
  claimRef:
    namespace: inregistrare-marca
    name: data-marca-mysql-0
