apiVersion: v1
kind: PersistentVolume
metadata:
  name: marca-mysql-data
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: marca-local
  hostPath:
    path: /home/storage/ns/marca-inregistrata
    type: DirectoryOrCreate
  claimRef:
    namespace: marca-inregistrata
    name: data-marca-mysql-0
