apiVersion: v1
kind: ConfigMap
metadata:
  name: marca-web-config
  namespace: inregistrare-marca
data:
  NUXT_PUBLIC_API_BASE_URL: ""
  NUXT_PUBLIC_GOOGLE_CLIENT_ID: "501838652278-q9f3j3icg9nf99c4ucedbe0rvvaurneh.apps.googleusercontent.com"
