name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 20

      - run: npm i -g --force corepack@latest && corepack enable

      - name: Install dependencies
        run: npx nypm@latest i
        working-directory: web

      - name: Lint
        run: npm run lint
        working-directory: web

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 20

      - run: npm i -g --force corepack@latest && corepack enable

      - name: Install dependencies
        run: npx nypm@latest i
        working-directory: web

      - name: Build
        run: npm run build
        working-directory: web
